version: "3.9"
services:
  epm:
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      euclidean.pointing.machine: "Euclidean pointing machine"
    tty: true
    ports:
      - "$HOST_HTTP_PORT:8080"
      - "$HOST_HTTPS_PORT:8443"